version: "3.6"
services:

  lexicon-db:
    container_name: "lexicon-db"
    image: "microsoft/mssql-server-linux:2017-CU13"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123  
    ports:
      - "1433:1433"

  lexicon-git-clone:
    container_name: "lexicon-git-clone"
    build: ./git-clone
    image: git_clone
    volumes:
      - flyway_sql:/flyway/sql
      - flyway_raw_sql:/git_raw_sql
      - flyway_raw_code:/git_raw_code
    depends_on:
      - lexicon-db 
      
  lexicon-baseline:
    container_name: "lexicon-baseline"
    image: "boxfuse/flyway:5.1"
    command: -url=jdbc:jtds:sqlserver://lexicon-db:1433/lexicon -user=sa -password=Password123 baseline
    depends_on:
      - lexicon-git-clone

  lexicon-migrate:
    container_name: "lexicon-migrate"
    image: "boxfuse/flyway:5.1"
    command: -url=jdbc:jtds:sqlserver://lexicon-db:1433/lexicon -user=sa -password=Password123 migrate
    volumes:
      - flyway_sql:/flyway/sql
    depends_on:
      - lexicon-baseline

  lexicon-webmvc:
    container_name: "lexicon-webmvc"
    build:
      context: ./../../
      dockerfile: ./Docs/Docker-Compose-Lexicon/webmvc/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - flyway_raw_code:/git_raw_code

volumes:
    flyway_sql:
    flyway_raw_sql:
    flyway_raw_code: